/// Flutter icons EduTeensIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EduTeensIcons
///      fonts:
///       - asset: fonts/EduTeensIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EduTeensIcons {
  EduTeensIcons._();

  static const _kFontFam = 'EduTeensIcons';
  static const String? _kFontPkg = null;

  static const IconData sistema = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sol = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tercer_puesto = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usuario = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verificado = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vista_tabla = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abajo = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alerta = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apagar = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apuntador = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apuntador_diagonal = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arriba = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ayuda = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basura = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buscar = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendario = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candado = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cargando = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carpeta_abierta = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carpeta_cerrada = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData celebracion = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cerrar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cerrar_sesion = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circulo_check = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clic_emocionado = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colapsar = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computadora = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computadora_mas = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computadora_modificando = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copiar = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corona = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correo = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correo_institucional = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cuadros = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cumplea_os = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData derecha = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData derecha_2 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData descarga = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData descolapsar = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diagonal = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dinero = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direccion = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editar = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enlace = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entendido = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equis = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamacion = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filtros = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grafica = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grupo = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horas = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_2 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iniciar_sesi_n = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inicio = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData izquierda = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData izquierda_2 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData llave = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lugar = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lugar_2 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mas = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mas_opciones_horizontal = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mas_opciones_vertical = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maximizar = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menos = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mensaje = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minimizar_parcial = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_quiero = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificacion = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificacion_activa = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_verificado = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData numero = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ojo = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ojo_cerrado = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ordenar_por = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paleta_colores = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData porcentaje = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portal_quipu = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primer_puesto = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promocion = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reintentar = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData segundo_puesto = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
